{
  package_type: 'library',
  public_include_directories: [
    'public',
  ],
  source_directories: [
    'source',
  ],
  dependencies+: [
    'facebook yoga',
    'google skia',
    'nlohmann json',
    'perception',
    'Perception Window',
  ],
} + (if is_testing then {
  dependencies+: [
    'perception',
  ],
  files_to_ignore: [
    'source/perception/ui/color_space.cc',
    'source/perception/ui/file_icon.cc',
    'source/perception/ui/font.cc',
    'source/perception/ui/font_manager.cc',
    'source/perception/ui/image.cc',
    'source/perception/ui/layout.cc',
    'source/perception/ui/measurements.cc',
    'source/perception/ui/node.cc',
    'source/perception/ui/node_serialization.cc',
    'source/perception/ui/shapes.cc',
    'source/perception/ui/text_alignment.cc',
    'source/perception/ui/text_handling.cc',
    'source/perception/ui/theme.cc',
    'source/perception/ui/components/block.cc',
    'source/perception/ui/components/button.cc',
    'source/perception/ui/components/checkbox.cc',
    'source/perception/ui/components/color_picker_dialog.cc',
    'source/perception/ui/components/combo_box.cc',
    'source/perception/ui/components/container.cc',
    'source/perception/ui/components/drop_down.cc',
    'source/perception/ui/components/focusable.cc',
    'source/perception/ui/components/image.cc',
    'source/perception/ui/components/image_view.cc',
    'source/perception/ui/components/input_box.cc',
    'source/perception/ui/components/label.cc',
    'source/perception/ui/components/open_file_dialog.cc',
    'source/perception/ui/components/pop_up.cc',
    'source/perception/ui/components/resizable_container.cc',
    'source/perception/ui/components/scroll_bar.cc',
    'source/perception/ui/components/scroll_container.cc',
    'source/perception/ui/components/slider.cc',
    'source/perception/ui/components/tab_bar.cc',
    'source/perception/ui/components/table.cc',
    'source/perception/ui/components/text_field.cc',
    'source/perception/ui/components/title_bar.cc',
    'source/perception/ui/components/tooltip.cc',
    'source/perception/ui/components/tree_view.cc',
    'source/perception/ui/components/ui_window.cc',
  ],
} else {})
